version: 2

node_key: &node_key
  key: node-deps-{{ arch }}-{{ checksum "package-lock.json" }}

restore_node: &restore_node
  restore_cache:
    <<: *node_key

install_node: &install_node
  run:
    name: node deps
    command: |
      if [ ! -d node_modules ]; then
        npm i --no-package-lock
      fi

save_node: &save_node
  save_cache:
    <<: *node_key
    paths:
      - node_modules

bower_key: &bower_key
  key: node-deps-{{ arch }}-{{ checksum "bower.json" }}

restore_bower: &restore_bower
  restore_cache:
    <<: *bower_key

install_bower: &install_bower
  run:
    name: bower deps
    command: |
      if [ ! -d bower_components ]; then
        npx bower i
      fi

save_bower: &save_bower
  save_cache:
    <<: *bower_key
    paths:
      - bower_components

container_defaults: &defaults
  docker:
    - image: circleci/node:8.7-browsers
      environment:
        JOBS: 2

jobs:
  install:
    <<: *defaults
    steps:
      - checkout

      - <<: *restore_node
      - <<: *install_node
      - <<: *save_node

      - <<: *restore_bower
      - <<: *install_bower
      - <<: *save_bower

  test:
    <<: *defaults

    steps:
      - checkout
      - <<: *restore_node
      - <<: *restore_bower
      - run: npx ember test

  deploy:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "67:0b:66:cf:5a:07:a4:9c:24:8f:71:f8:34:2f:a5:0f"
      - checkout
      - <<: *restore_node
      - <<: *restore_bower
      - deploy:
         name: Deploy to GitHub Pages
         command: npx ember deploy production

workflows:
  version: 2
  just-test:
    jobs:
      - install:
          filters:
            branches:
              ignore: master
      - test:
          requires:
            - install

  test-and-deploy:
    jobs:
      - install:
          filters:
            branches:
              only: master
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
