version: 2

node_key: &node_key
  key: node-deps-{{ arch }}-{{ checksum "package-lock.json" }}

restore_node: &restore_node
  restore_cache:
    <<: *node_key

install_node: &install_node
  run:
    name: node deps
    command: |
      if [ ! -d node_modules ]; then
        npm i --no-package-lock
      fi

save_node: &save_node
  save_cache:
    <<: *node_key
    paths:
      - node_modules

container_defaults: &defaults
  docker:
    - image: circleci/node:8.7-browsers
      environment:
        JOBS: 2

jobs:
  install:
    <<: *defaults
    steps:
      - checkout

      - <<: *restore_node
      - <<: *install_node
      - <<: *save_node

  test:
    <<: *defaults

    steps:
      - checkout
      - <<: *restore_node

      - run: npx ember test

  deploy:
    <<: *defaults
    steps:
      - deploy:
         name: Deploy to GitHub Pages
         command: npx ember deploy production

workflows:
  version: 2
  just-test:
    jobs:
      - install:
          filters:
            branches:
              ignore: master
      - test:
          requires:
            - install

  test-and-deploy:
    jobs:
      - install:
          filters:
            branches:
              only: master
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
